<a href="https://colab.research.google.com/github/Mamun-75/Python-For-Data-Science-and-Machine-Learning/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# open source library built on top of numpy

In [4]:
"""
it allows for fast analysis and data cleaning and preparation
it excels in performance and productivity
it also has built in visualization features, it can work with data from a wide variety of sources
"""

'\nit allows for fast analysis and data cleaning and preparation\nit excels in performance and productivity\nit also has built in visualization features, it can work with data from a wide variety of sources\n'

In [5]:
# series very similar to numpy array, actually built in top of numpy array object
# what differentiates is series can be indexed by a label
import numpy as np
import pandas as pd

In [6]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [7]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [10]:
## more ways to create a series

In [11]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(arr, labels) # by passing a numpy array, we also can pass labels

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(d) ## by passing a dictionary , it automatically take the keys of that dictionary as index, and values as corresponding data point

a    10
b    20
c    30
dtype: int64

In [14]:
## another thing that differentiate a numpy array from series is that
## a series  can hold a variety of object types,
#  such as number string , even built in functions as data point

labels

['a', 'b', 'c']

In [15]:
pd.Series(data = labels)

0    a
1    b
2    c
dtype: object

In [16]:
pd.Series(data = [sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [17]:
## how to grab information from a series

In [18]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [19]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [20]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])

In [21]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [22]:
ser1['USA'] ## we need to pass index label, it will show us corresponding data

np.int64(1)

In [23]:
ser3 = pd.Series(data = labels)

In [24]:
ser3[0]

'a'

In [25]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [26]:
# note: in series operation, integers are converted to float so we don't accidentally lose information based on some weird division

Dataframe

In [27]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [28]:
np.random.seed(101)  # seed generates the same random numbers

In [29]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [30]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df['W']  # this 'W' column is a series

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [32]:
type(df['W'])

pandas.core.series.Series

In [33]:
type(df)

pandas.core.frame.DataFrame

In [34]:
### so a dataframe is a bunch of series that share the same index

In [35]:
df[['W','Z']]   # so when we ask for multiple columns i am actually getting back a data frame, and when i ask for a single column, then i get back a series

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [36]:
## 2 different way to grab a column from a dataframe
# first way and we always should do it
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [37]:
df.W ## it will also work , but it may create confusion with available methods

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [38]:
df['new']  = df['W'] + df['Y']  # add new column

In [39]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [40]:
## dropping  a column
df.drop('new', axis = 1, inplace = True)  # axis is must, and inplace ensure that the column is deleted from the original dataframe
                                          # inplace prevent losing data accidentally

In [41]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df.drop('E', axis = 0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [43]:
df.shape ## this is why rows are reffered to as the 0 axis, and columns are referred to as the 1 axis

(5, 4)

In [44]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [45]:
## selecting rows --- 2 ways

In [46]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [47]:
df.loc['A'] ## rows are series as well!, loc for label based index

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [48]:
df.iloc[2] # iloc for numerical based index

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [49]:
df.loc['B' ,'Y' ] ## subsetting rows and columns

np.float64(-0.8480769834036315)

In [50]:
df.loc[['A','B'],['W','Y']] ## subsetting rows and columns

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [51]:
 ## conditional selection and this is very similar to numpy

In [52]:
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [53]:
booldf =  df > 0

In [54]:
booldf

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [55]:
df[booldf]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [56]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [57]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [58]:
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [59]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [60]:
df[df['W'] > 0]   # it will show only true value

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [61]:
df[df['Z'] < 0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [62]:
resultdf = df[df['W'] > 0]

In [63]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [64]:
df[df['W'] > 0]['X']  ## in one step

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [65]:
df[df['W'] > 0][['Y','X']]  # one line

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [66]:
## multiple line
boolser = df['W'] > 0
result = df[boolser]
mycols = ['Y','X']
result[mycols]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [67]:
df[(df['W']>0) & (df['Y']>1)]  #instead of 'and' we need to use & , normal and get confused , and cant deal with pandas

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [68]:
df[(df['W']>0) | (df['Y']>1)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [69]:
# resetting index
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [70]:
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [71]:
newind = 'CA NY WY OR CO'.split()

In [72]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [73]:
df['States'] =  newind

In [74]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [75]:
df.set_index('States')

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [76]:
# multi indexed dataframe

import numpy as np
import pandas as pd

In [77]:
 #index levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [78]:
df =  pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [79]:
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [80]:
df.loc['G1']

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [81]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [82]:
df.index.names = ['Groups','Num']

In [83]:
df

                   A         B
Groups Num
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [84]:
df.loc['G2'].loc[2]['B']

np.float64(0.07295967531703869)

In [85]:
df.loc['G1'].loc[1]['B']

np.float64(1.693722925204035)

cross section very useful function

In [86]:
df.xs('G1')

            A         B
Num
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

cross section work like loc , but it offer more flexibility , we use it to find index in stock exchange data, its not very common

In [87]:
df.xs(1,level = 'Num')

               A         B
Groups
G1      0.302665  1.693723
G2      0.166905  0.184502

Missing Data handling

In [88]:
import numpy as np
import pandas as pd

In [89]:
d = {'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[1,2,3] }

In [90]:
df = pd.DataFrame(d)

In [91]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [92]:
df.dropna()  ## it drops any row with any single or more missing values, by default axis  = 0 means , row

     A    B  C
0  1.0  5.0  1

In [93]:
df.dropna(axis = 1) ## it drops any column with any single or more missing values

   C
0  1
1  2
2  3

In [94]:
df.dropna(thresh = 2) ## it keeps row which has at least 2 non null value

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [95]:
df.dropna(thresh =3 ) ## it keeps row which has at least 3 non null value

     A    B  C
0  1.0  5.0  1

In [96]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [97]:
df.fillna(value = 'FILL VALUE')  ## fill missing value

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [98]:
df['A'].fillna(value = df['A'].mean())  ## fill with mean value of A column

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

Group By
group together rows based off of a column and perform an aggregate function on them

In [99]:
import numpy as np
import pandas as pd

In [100]:
data = {'Company': ['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Sales':[200,120,340,124,243,350]}

In [101]:
df = pd.DataFrame(data)

In [102]:
df

  Company   person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [103]:
byComp = df.groupby('Company')

In [104]:
byComp['Sales'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [105]:
byComp.sum()

             person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [106]:
byComp['Sales'].std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [107]:
byComp.sum().loc['FB']

person    CarlSarah
Sales           593
Name: FB, dtype: object

In [108]:
df.groupby('Company').count()

         person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [109]:
df.groupby('Company').max()

          person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [110]:
df.groupby('Company').min()

          person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [111]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [112]:
df.groupby('Company').describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

merging , joining , and concatenating

In [113]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']},
                    index = [0,1,2,3])

In [114]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7']},
                    index = [4,5,6,7])

In [115]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C':['C8','C9','C10','C11'],
                    'D':['D8','D9','D10','D11']},
                    index = [8,9,10,11])

In [116]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [117]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [118]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [119]:
## concatenation basically glues together DataFrames. dimensions should be match along the axix we are concatenating on.
## we use pd.concat and pass in a list of Data Frames to concatenate together

In [120]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [121]:
pd.concat([df1,df2,df3], axis = 1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [122]:
left = pd.DataFrame({'key': ['K0','K1','K2','K3'],
                     'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']})

right = pd.DataFrame({'key': ['K0','K1','K2','K3'],
                      'C':['C0','C1','C2','C3'],
                      'D':['D0','D1','D2','D3']})

In [123]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [124]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

Merging

In [125]:

## the merge function allows you to merge dataframes together using a similar logic as merging sql tables together for example:
## instead of gluing the dataframe pd.merge see where the values match up on columns
## by default we get inner merge

In [126]:
pd.merge(left,right,how = 'inner', on = 'key')   ## merging on key column

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [127]:
left = pd.DataFrame ({'key1':['k0','k0', 'k1','k1'],
                      'key2':['k0','k1','k0','k1'],
                      'A':['A0','A1','A2','A3'],
                      'B':['B0','B1','B2','B3']})
right = pd.DataFrame ({'key1':['k0','k1', 'k1','k2'],
                      'key2':['k0','k0','k0','k0'],
                       'C': ['C0','C1','C2','C3'],
                       'D': ['D0','D1','D2','D3']})

In [128]:
left

  key1 key2   A   B
0   k0   k0  A0  B0
1   k0   k1  A1  B1
2   k1   k0  A2  B2
3   k1   k1  A3  B3

In [129]:
right

  key1 key2   C   D
0   k0   k0  C0  D0
1   k1   k0  C1  D1
2   k1   k0  C2  D2
3   k2   k0  C3  D3

In [130]:
pd.merge(left,right, on = ['key1','key2'])

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A2  B2  C1  D1
2   k1   k0  A2  B2  C2  D2

In [131]:
pd.merge(left,right, how = 'outer', on = ['key1','key2'])

  key1 key2    A    B    C    D
0   k0   k0   A0   B0   C0   D0
1   k0   k1   A1   B1  NaN  NaN
2   k1   k0   A2   B2   C1   D1
3   k1   k0   A2   B2   C2   D2
4   k1   k1   A3   B3  NaN  NaN
5   k2   k0  NaN  NaN   C3   D3

In [132]:
pd.merge(left, right, how = 'right', on = ['key1','key2'])  ## study details about how

  key1 key2    A    B   C   D
0   k0   k0   A0   B0  C0  D0
1   k1   k0   A2   B2  C1  D1
2   k1   k0   A2   B2  C2  D2
3   k2   k0  NaN  NaN  C3  D3

In [133]:
pd.merge(left, right, how = 'left', on = ['key1','key2'] )  ## study details about how

  key1 key2   A   B    C    D
0   k0   k0  A0  B0   C0   D0
1   k0   k1  A1  B1  NaN  NaN
2   k1   k0  A2  B2   C1   D1
3   k1   k0  A2  B2   C2   D2
4   k1   k1  A3  B3  NaN  NaN

joining

In [134]:
## joining is a convenient method for combining rhe columns of two potentially differently indexed dataframes into a single result DataFrame

In [135]:
left = pd.DataFrame({'A':['A0','A1','A2'],
                    'B':['B0','B1','B2']},
                    index = ['K0','K1','k2'])
left = pd.DataFrame({'C':['C0','C2','C3'],
                    'D':['D0','D2','D3']},
                    index = ['K0','K2','K3'])

In [136]:
left.join(right, lsuffix='_left', rsuffix='_right')

   C_left D_left key1 key2 C_right D_right
K0     C0     D0  NaN  NaN     NaN     NaN
K2     C2     D2  NaN  NaN     NaN     NaN
K3     C3     D3  NaN  NaN     NaN     NaN

In [137]:
left.join(right, how = 'outer', lsuffix='_left', rsuffix='_right')

   C_left D_left key1 key2 C_right D_right
K0     C0     D0  NaN  NaN     NaN     NaN
K2     C2     D2  NaN  NaN     NaN     NaN
K3     C3     D3  NaN  NaN     NaN     NaN
0     NaN    NaN   k0   k0      C0      D0
1     NaN    NaN   k1   k0      C1      D1
2     NaN    NaN   k1   k0      C2      D2
3     NaN    NaN   k2   k0      C3      D3

In [138]:
## we need to learn differences between concatenation, merge and join, and when we use which one, based on  context, little bit of theory

operations

In [139]:
import numpy as np
import pandas as pd

In [140]:
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [141]:
df['col2'].unique()  # this is for checking unique values

array([444, 555, 666])

In [142]:
df['col2'].nunique() # checking the number of values

3

In [143]:
df['col2'].value_counts() # checking the number of values

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [144]:
### selecting data , reemphasizing conditional selection
df[df['col1']>2]

   col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [145]:
df['col1']>2

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [146]:
df[(df['col1']>2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz

In [147]:
### apply method
def times2(x):
    return x*2

In [148]:
df['col1'].sum()

np.int64(10)

In [149]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [150]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [151]:
### apply is very powerful when we combine it with lambda expression

In [152]:
df['col2'].apply(lambda x: x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [153]:
## removing columns

In [154]:
df.drop('col1', axis = 1, inplace  = True)  ##we have to mention axis =  1 to drop the column, we need to specify inplace to drop permanantly

In [155]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [156]:
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [157]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [158]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [159]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [160]:
df.sort_values(by = 'col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [161]:
df.isnull() ## a really useful method to find no values in the data frame

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [162]:
#pivot table
data = {'A':['foo','foo','foo','bar','bar','bar'],
        'B':['one','one','two','two','one','one'],
        'C':['x','y','x','y','x','y'],
        'D':[1,3,2,5,4,1]}
df = pd.DataFrame(data)

In [163]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [164]:
df.pivot_table(values = 'D', index = ['A','B'], columns = ['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [165]:
## study more on pivot table  ,make the concept easier

Data input and Output

In [166]:
## we are going to learn csv, excel, html, sql

csv files

In [175]:
df = pd.read_csv('example.csv')

In [178]:
df

  Username; Identifier;First name;Last name
0               booker12;9012;Rachel;Booker
1                    grey07;2070;Laura;Grey
2              johnson81;4081;Craig;Johnson
3               jenkins46;9346;Mary;Jenkins
4                  smith79;5079;Jamie;Smith

In [183]:
df.to_csv('My_output', index = False)

In [187]:
df = pd.read_csv('My_output')

excel file

In [193]:
pd.read_excel('file_example_XLSX.xlsx', sheet_name = 'Sheet1')

     0 First Name   Last Name  Gender        Country  Age        Date    Id
0    1      Dulce       Abril  Female  United States   32  15/10/2017  1562
1    2       Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
2    3     Philip        Gent    Male         France   36  21/05/2015  2587
3    4   Kathleen      Hanner  Female  United States   25  15/10/2017  3549
4    5    Nereida     Magwood  Female  United States   58  16/08/2016  2468
5    6     Gaston       Brumm    Male  United States   24  21/05/2015  2554
6    7       Etta        Hurn  Female  Great Britain   56  15/10/2017  3598
7    8    Earlean      Melgar  Female  United States   27  16/08/2016  2456
8    9   Vincenza     Weiland  Female  United States   40  21/05/2015  6548
9   10     Fallon     Winward  Female  Great Britain   28  16/08/2016  5486
10  11    Arcelia      Bouska  Female  Great Britain   39  21/05/2015  1258
11  12   Franklyn      Unknow    Male         France   38  15/10/2017  2579
12  13    Sherron    Ascencio  Female  Great Britain   32  16/08/2016  3256
13  14     Marcel   Zabriskie    Male  Great Britain   26  21/05/2015  2587
14  15       Kina    Hazelton  Female  Great Britain   31  16/08/2016  3259
15  16   Shavonne         Pia  Female         France   24  21/05/2015  1546
16  17     Shavon      Benito  Female         France   39  15/10/2017  3579
17  18   Lauralee     Perrine  Female  Great Britain   28  16/08/2016  6597
18  19     Loreta      Curren  Female         France   26  21/05/2015  9654
19  20     Teresa      Strawn  Female         France   46  21/05/2015  3569
20  21    Belinda     Partain  Female  United States   37  15/10/2017  2564
21  22      Holly        Eudy  Female  United States   52  16/08/2016  8561
22  23       Many      Cuccia  Female  Great Britain   46  21/05/2015  5489
23  24     Libbie       Dalby  Female         France   42  21/05/2015  5489
24  25     Lester     Prothro    Male         France   21  15/10/2017  6574
25  26     Marvel        Hail  Female  Great Britain   28  16/08/2016  5555
26  27    Angelyn        Vong  Female  United States   29  21/05/2015  6125
27  28  Francesca   Beaudreau  Female         France   23  15/10/2017  5412
28  29      Garth       Gangi    Male  United States   41  16/08/2016  3256
29  30      Carla    Trumbull  Female  Great Britain   28  21/05/2015  3264
30  31       Veta       Muntz  Female  Great Britain   37  15/10/2017  4569
31  32     Stasia      Becker  Female  Great Britain   34  16/08/2016  7521
32  33       Jona     Grindle  Female  Great Britain   26  21/05/2015  6458
33  34      Judie    Claywell  Female         France   35  16/08/2016  7569
34  35     Dewitt      Borger    Male  United States   36  21/05/2015  8514
35  36       Nena      Hacker  Female  United States   29  15/10/2017  8563
36  37     Kelsie     Wachtel  Female         France   27  16/08/2016  8642
37  38        Sau        Pfau  Female  United States   25  21/05/2015  9536
38  39    Shanice   Mccrystal  Female  United States   36  21/05/2015  2567
39  40      Chase      Karner    Male  United States   37  15/10/2017  2154
40  41     Tommie   Underdahl    Male  United States   26  16/08/2016  3265
41  42     Dorcas      Darity  Female  United States   37  21/05/2015  8765
42  43      Angel       Sanor    Male         France   24  15/10/2017  3259
43  44  Willodean        Harn  Female  United States   39  16/08/2016  3567
44  45     Weston     Martina    Male  United States   26  21/05/2015  6540
45  46       Roma  Lafollette  Female  United States   34  15/10/2017  2654
46  47     Felisa        Cail  Female  United States   28  16/08/2016  6525
47  48   Demetria       Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy        Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

In [194]:
df.to_excel('Excel_sample2.xlsx', sheet_name = 'NewSheet')

In [198]:
df.head()

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

html file

In [199]:
data = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [204]:
data[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549

SQL

In [205]:
from sqlalchemy import create_engine

In [206]:
engine = create_engine('sqlite:///:memory:')

In [207]:
df.to_sql('my_table', engine)

50

In [208]:
sqldf = pd.read_sql('my_table', con = engine)

In [210]:
sqldfy

,index,0,First Name,Last Name,Gender,Country,Age,Date,Id
0,0,1,Dulce,Abril,Female,United States,32,15/10/2017,1562
1,1,2,Mara,Hashimoto,Female,Great Britain,25,16/08/2016,1582
2,2,3,Philip,Gent,Male,France,36,21/05/2015,2587
3,3,4,Kathleen,Hanner,Female,United States,25,15/10/2017,3549
4,4,5,Nereida,Magwood,Female,United States,58,16/08/2016,2468
5,5,6,Gaston,Brumm,Male,United States,24,21/05/2015,2554
6,6,7,Etta,Hurn,Female,Great Britain,56,15/10/2017,3598
7,7,8,Earlean,Melgar,Female,United States,27,16/08/2016,2456
8,8,9,Vincenza,Weiland,Female,United States,40,21/05/2015,6548
9,9,10,Fallon,Winward,Female,Great Britain,28,16/08/2016,5486
10,10,11,Arcelia,Bouska,Female,Great Britain,39,21/05/2015,1258
11,11,12,Franklyn,Unknow,Male,France,38,15/10/2017,2579
12,12,13,Sherron,Ascencio,Female,Great Britain,32,16/08/2016,3256
13,13,14,Marcel,Zabriskie,Male,Great Britain,26,21/05/2015,2587
14,14,15,Kina,Hazelton,Female,Great Britain,31,16/08/2016,3259
15,15,16,Shavonne,Pia,Female,France,24,21/05/2015,1546
16,16,17,Shavon,Benito,Female,France,39,15/10/2017,3579
17,17,18,Lauralee,Perrine,Female,Great Britain,28,16/08/2016,6597
18,18,19,Loreta,Curren,Female,France,26,21/05/2015,9654
19,19,20,Teresa,Strawn,Female,France,46,21/05/2015,3569
20,20,21,Belinda,Partain,Female,United States,37,15/10/2017,2564
21,21,22,Holly,Eudy,Female,United States,52,16/08/2016,8561
22,22,23,Many,Cuccia,Female,Great Britain,46,21/05/2015,5489
23,23,24,Libbie,Dalby,Female,France,42,21/05/2015,5489
24,24,25,Lester,Prothro,Male,France,21,15/10/2017,6574
25,25,26,Marvel,Hail,Female,Great Britain,28,16/08/2016,5555
26,26,27,Angelyn,Vong,Female,United States,29,21/05/2015,6125
27,27,28,Francesca,Beaudreau,Female,France,23,15/10/2017,5412
28,28,29,Garth,Gangi,Male,United States,41,16/08/2016,3256
29,29,30,Carla,Trumbull,Female,Great Britain,28,21/05/2015,3264
30,30,31,Veta,Muntz,Female,Great Britain,37,15/10/2017,4569
31,31,32,Stasia,Becker,Female,Great Britain,34,16/08/2016,7521
32,32,33,Jona,Grindle,Female,Great Britain,26,21/05/2015,6458
33,33,34,Judie,Claywell,Female,France,35,16/08/2016,7569
34,34,35,Dewitt,Borger,Male,United States,36,21/05/2015,8514
35,35,36,Nena,Hacker,Female,United States,29,15/10/2017,8563
36,36,37,Kelsie,Wachtel,Female,France,27,16/08/2016,8642
37,37,38,Sau,Pfau,Female,United States,25,21/05/2015,9536
38,38,39,Shanice,Mccrystal,Female,United States,36,21/05/2015,2567
39,39,40,Chase,Karner,Male,United States,37,15/10/2017,2154
40,40,41,Tommie,Underdahl,Male,United States,26,16/08/2016,3265
41,41,42,Dorcas,Darity,Female,United States,37,21/05/2015,8765
42,42,43,Angel,Sanor,Male,France,24,15/10/2017,3259
43,43,44,Willodean,Harn,Female,United States,39,16/08/2016,3567
44,44,45,Weston,Martina,Male,United States,26,21/05/2015,6540
45,45,46,Roma,Lafollette,Female,United States,34,15/10/2017,2654
46,46,47,Felisa,Cail,Female,United States,28,16/08/2016,6525
47,47,48,Demetria,Abbey,Female,United States,32,21/05/2015,3265
48,48,49,Jeromy,Danz,Male,United States,39,15/10/2017,3265
49,49,50,Rasheeda,Alkire,Female,United States,29,16/08/2016,6125